// GlobalComponents for Volar
declare module 'vue' {
  export interface GlobalComponents {
    WpPopover: typeof import('wisdom-plus')['WpPopover']
    WpButton: typeof import('wisdom-plus')['WpButton']
    WpCollapse: typeof import('wisdom-plus')['WpCollapse']
    WpCollapseItem: typeof import('wisdom-plus')['WpCollapseItem']
    CollapseTransition: typeof import('wisdom-plus')['CollapseTransition']
    WpG: typeof import('wisdom-plus')['WpGrid']
    WpGrid: typeof import('wisdom-plus')['WpGrid']
    WpGridItem: typeof import('wisdom-plus')['WpGridItem']
    WpGi: typeof import('wisdom-plus')['WpGridItem']
    WpSpace: typeof import('wisdom-plus')['WpSpace']
    WpIcon: typeof import('wisdom-plus')['WpIcon']
    WpTooltip: typeof import('wisdom-plus')['WpTooltip']
    WpMenu: typeof import('wisdom-plus')['WpMenu']
    WpScrollList: typeof import('wisdom-plus')['WpScrollList']
    WpEllipsis: typeof import('wisdom-plus')['WpEllipsis']
    WpStatistic: typeof import('wisdom-plus')['WpStatistic']
    WpOverlay: typeof import('wisdom-plus')['WpOverlay']
    WpPopConfirm: typeof import('wisdom-plus')['WpPopConfirm']
    WpDropdown: typeof import('wisdom-plus')['WpDropdown']
    WpActionSheet: typeof import('wisdom-plus')['WpActionSheet']
    WpTag: typeof import('wisdom-plus')['WpTag']
    WpTagInput: typeof import('wisdom-plus')['WpTagInput']
    WpLayout: typeof import('wisdom-plus')['WpLayout']
    WpLayoutContent: typeof import('wisdom-plus')['WpLayoutContent']
    WpLayoutAside: typeof import('wisdom-plus')['WpLayoutAside']
    WpBreadcrumb: typeof import('wisdom-plus')['WpBreadcrumb']
    WpAvatar: typeof import('wisdom-plus')['WpAvatar']
    WpVirtualList: typeof import('wisdom-plus')['WpVirtualList']
    WpProgress: typeof import('wisdom-plus')['WpProgress']
    WpRadio: typeof import('wisdom-plus')['WpRadio']
    WpRadioGroup: typeof import('wisdom-plus')['WpRadioGroup']
    WpCheckbox: typeof import('wisdom-plus')['WpCheckbox']
    WpXScroll: typeof import('wisdom-plus')['WpXScroll']
    WpCheckboxGroup: typeof import('wisdom-plus')['WpCheckboxGroup']
    WpTree: typeof import('wisdom-plus')['WpTree']
    WpModal: typeof import('wisdom-plus')['WpModal']
    WpDialog: typeof import('wisdom-plus')['WpDialog']
    WpDrawer: typeof import('wisdom-plus')['WpDrawer']
    WpUpload: typeof import('wisdom-plus')['WpUpload']
    WpCountTo: typeof import('wisdom-plus')['WpCountTo']
    WpPagination: typeof import('wisdom-plus')['WpPagination']
  }
}

export {}
